---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}


# loading the required libraries
library("jpeg")
library("ggplot2")
library("grid")

#source("/data/Project/Project1/program_meta_final/step0_load_data.R")

load("/data/Project/Project1/result_new/rdata/load_all_files.rdata")
source("/data/Project/functions/functions_plot.r")
##############################Plot flowchart
xpos <- 1:5
ypos <- xpos**2
data_frame = data.frame(xpos = xpos,
ypos = ypos)

print ("Data points")
print (data_frame)
library(tiff)
path <- "/data/Project/Project1/figures/figure1a.tif"
img <- readTIFF(path, native = TRUE)
img <- rasterGrob(img, interpolate=TRUE)
# plotting the data
p1_flowchart=qplot(xpos, ypos, geom="blank") +
annotation_custom(img, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
geom_point(color=I("White"))+theme_void()

##############################Plot Umap
umap = combined.sct_filter@reductions$umap@cell.embeddings %>%  as.data.frame() %>% 
  cbind(cell_type =combined.sct_filter@meta.data$Cell_type,class_new=combined.sct_filter@meta.data$class_new) 

cell_type_med <- umap %>%
  group_by(cell_type) %>%
  summarise(
    UMAP_1 = median(UMAP_1),
    UMAP_2 = median(UMAP_2)
  )


p2_umap=DimPlot(combined.sct_filter, label = F,group.by = "class_new")+ggtitle("Metabolic genes")+scale_color_manual(values = c("#00BFFF", "#EE7621"))+
          theme_void(base_size = 14, base_family = "Helvetica")

p2_umap=p2_umap + geom_segment(aes(x = min(umap$UMAP_1) , y = min(umap$UMAP_2) ,xend = min(umap$UMAP_1) +5, yend = min(umap$UMAP_2) ),colour = "black", size=0.1,arrow = arrow(length = unit(0.2,"cm")))+ 
          geom_segment(aes(x = min(umap$UMAP_1)  , y = min(umap$UMAP_2)  ,xend = min(umap$UMAP_1) , yend = min(umap$UMAP_2) + 5),colour = "black", size=0.1,arrow = arrow(length = unit(0.2,"cm")))+
          annotate("text", x = min(umap$UMAP_1) +4, y = min(umap$UMAP_2) -1.5, label = "UMAP 1",color="black",size = 4.7 ) + 
          annotate("text", x = min(umap$UMAP_1) -1.5, y = min(umap$UMAP_2) + 4, label = "UMAP 2",color="black",size = 4.7, angle=90) +
          geom_text(aes(label=cell_type,x=UMAP_1,y=UMAP_2,size=I(4.7),fontface="plain"),data = cell_type_med)+theme(plot.title = element_text(lineheight=.8, size=14, hjust = 0.5) ,plot.margin = unit(c(1,1,1,1), "cm"),legend.text = element_text(size=14))
 
########################################plot marker gene dotplot

markers<-as.data.frame(rbind(cbind(cell="B cell",gene=c("MS4A1","CD19")),         cbind(cell="Plasma",gene=c("CD79A","MZB1","JCHAIN")),
                             cbind(cell="T cell",gene=c("CD3E", "CD3D", "CD3G")),
                             cbind(cell="Epithelial",gene=c("EPCAM", "MUC1", "CDH1" )),
                             cbind(cell="Mast",gene=c("HDC", "CPA3", "TPSAB1")),
                             cbind(cell="Myeloid",gene=c("FCGR3A", "CD14", "CD163")),
                             cbind(cell="Endothelial",gene=c("PECAM1","VWF","CLDN5")),
                             cbind(cell="Fibroblast",gene=c("FBLN1", "PDGFRA","FGF7"))))


x<-split(markers$gene,markers$cell)
x=x[c(1,7,8,3,5,6,2,4)]

all_dataset_SCT_filter$cell_clustered<-factor(all_dataset_SCT_filter$cell_clustered,levels = c("B cell","Plasma","T cell","Epithelial","Mast" ,"Myeloid","Endothelial","Fibroblast"))
p1_dot=DotPlot(object = all_dataset_SCT_filter,features = x,group.by = "cell_clustered") +theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 0.5 ))+ggtitle("")


cc1=brewer.pal(n =8, name = "Set3")
cc1=cc1[c(1:4,8,5:7)]


p2_dot=DotPlot(object = all_dataset_SCT_filter,features = x,group.by = "cell_clustered",cols = c("lightgrey", "#EE7621"))+theme_hd_plain()+theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 0.5 ),strip.text = element_text(angle = 60),axis.title = element_blank(),legend.position = "right")+ggtitle("")+ guides(
    size = guide_legend( title = "Percent\nexpressed")
  )
p2_dot$guides$colour$title="Average\nexpression"




############################# plot cell type percentage barplot



x=as.matrix(table(paste(combined.sct_filter$class_new,combined.sct_filter$dataset,sep="_"),combined.sct_filter$Cell_type))
x1=apply(x,1,function(x) x/sum(x))
x2=reshape2::melt(x1)
x2$type=x2$Var2
 p3_cell=ggplot(x2,aes(x=Var2,fill=Var1,y=value))+geom_bar(stat = "identity")+theme_hd_plain()+theme(legend.position = "right")+xlab("Sample type")+ylab("Cell type composition")+labs(fill="Cell Type")+coord_flip()+scale_fill_manual(values=brewer.pal(n =8, name = "Set3")[c(1:4,8,5:7)])

############################# plot cell type percentage barplot

combined.sct_filter$Class<-combined.sct_filter$class_new
x=as.matrix(table(paste(combined.sct_filter$Class,combined.sct_filter$patient,combined.sct_filter$dataset,sep="_"),combined.sct_filter$Cell_type))
x1=apply(x,1,function(x) x/sum(x))
x2=reshape2::melt(x1)
x2$type=x2$Var2
 p3=ggplot(x2,aes(x=Var2,fill=Var1,y=value))+geom_bar(stat = "identity")+theme_hd()+theme(axis.text.x = element_text(angle = 90,size=6,hjust = 1))+ggtitle("Cell type composition")+xlab("Sample type")+ylab("Frequency")+labs(fill="Cell Type")
 
 ############################# plot cell type percentage boxplot
 x2$dataset=str_split_fixed(x2$Var2,"_",3)[,3]
x2$type=str_split_fixed(x2$Var2,"_",3)[,1]
p2_cell= ggplot(x2[x2$Var1!="Mast",],aes(x=type,y=value,color=dataset))+geom_boxplot()+theme_hd_plain()+theme(axis.text.x = element_text(angle = 30,hjust = 1),strip.text = element_text(angle = 60),plot.margin = unit(c(1,2,1,2), "cm"),axis.title.x = element_blank())+ylab("Cell type composition")+facet_wrap(~Var1,nrow=1)+geom_signif(
    comparisons = list(c("Normal","Tumor")),map_signif_level=T,color="black")+scale_color_manual(name="Dataset",values=c("#7FDBB3", "#F5AD75", "#85A4E6", "#F593CE", "#CAF77B"))


################################## Plot correlation heatmap

 all_gene_pathway<-readRDS(file ="/data/Project/Project1/data/all_genes_pathway_infor_select.rds")

 metagenes= unique(all_gene_pathway$gene)
all_genes=rownames(all_dataset_SCT_filter@assays$SCT@counts)
  raw_data<-as.matrix(all_dataset_SCT_filter@assays$SCT@counts[all_genes[all_genes %in% metagenes], ])
  merge_metaSCT_raw=all_dataset_SCT_filter@meta.data[colnames(all_dataset_SCT_filter@assays$SCT@counts),]
 mean_genes_raw<-aggregate(t(raw_data),list(s=as.character(merge_metaSCT_raw$Cell_type),p=merge_metaSCT_raw$dataset,type=merge_metaSCT_raw$class_new),function(x) mean(x))
 mean_genes_df_raw<- mean_genes_raw[,-c(1:3)]
 rownames(mean_genes_df_raw)<-paste(mean_genes_raw[,1],mean_genes_raw[,2],mean_genes_raw[,3],sep="_")
 cor_raw<-plotCorHeatmap2( mean_genes_df_raw,"Correlation")
 
 
 
################################# plot metabolic activity 
 
meta_data=all_dataset_SCT_filter@meta.data
meta_aggre<-aggregate(meta_data[,"metabolic_activity"],list(patient=meta_data$patient,type=meta_data$class_new,cell=meta_data$Cell_type,dataset=meta_data$dataset),mean)

p_mat<-ggplot(meta_aggre[meta_aggre$cell!="Mast",],aes(x=type,y=x,col=dataset))+geom_boxplot()+theme_hd_plain()+theme(axis.text.x = element_text(angle = 30,hjust = 1),plot.margin = unit(c(1,2,1,2), "cm"),strip.text = element_text(angle = 60),axis.title.x = element_blank())+ylab("Total metabolic activity")+facet_wrap(~cell,nrow=1)+scale_color_manual(name="Dataset",values=c("#7FDBB3", "#F5AD75", "#85A4E6", "#F593CE", "#CAF77B"))+geom_signif(comparisons = list(c("Normal","Tumor")),map_signif_level=T,color="black")






pall0=ggarrange(p1_flowchart,p2_umap,nrow = 1,ncol=2,labels =letters[1:2] ,font.label = list(size=18,color="black",face="bold"))


pall1<-ggarrange(p2_dot,p3_cell,nrow=2,ncol=1,heights = c(1.4,1),labels =letters[c(3,5)],font.label = list(size=18,color="black",face="bold"))

pall2=ggarrange(pall1,cor_raw$pp,labels =c("",letters[4]),font.label = list(size=18,color="black",face="bold"))

pall3=ggarrange(p2_cell,p_mat,labels =letters[6:7],font.label = list(size=18,color="black",face="bold"),common.legend = T,legend = "bottom")


figure1_p<-ggarrange(pall0,pall2,pall3,nrow=3,ncol=1,heights = c(1.2,1.4,1))

pdf(paste("/data/Project/Project1/figures/","figure1.pdf",sep=""),height  = 20,width = 18)
print(figure1_p)
dev.off()


tiff(paste("/data/Project/Project1/figures/","figure1.tiff",sep=""),height = 24,width = 19,res = 300,units="in",compression = "lzw")
print(figure1_p)
dev.off()




p_vln1<-VlnPlot(all_dataset_SCT_filter,features =  c("nFeature_RNA"),group.by = "patient",split.by = "class_new",pt.size = 0)+scale_fill_manual(values=c("#00BFFF", "#EE7621"))
p_vln2<-VlnPlot(all_dataset_SCT_filter,features = c("nCount_RNA"),group.by = "patient",split.by = "class_new",pt.size = 0)+scale_fill_manual(values=c("#00BFFF", "#EE7621"))
p_vln3<-VlnPlot(all_dataset_SCT_filter,features = c("percent.mt"),group.by = "patient",split.by = "class_new",pt.size = 0)+scale_fill_manual(values=c("#00BFFF", "#EE7621"))


plotVlnplot<-function(temp,labs_x,labs_xname){
  
patient_counts <- temp %>%
    group_by(dataset) %>%
    summarise(patient_count = n_distinct(patient), .groups = 'drop')

# 初始化一个列表来存储每个小提琴图
plots <- vector("list", nrow(patient_counts))

# 循环绘制每个 dataset 的小提琴图
for (i in 1:nrow(patient_counts)) {
    dataset_name <- patient_counts$dataset[i]
  
    # 绘制小提琴图
    p <- ggplot(temp %>% filter(dataset == dataset_name), aes(x = patient, y = get(labs_x), fill = class_new)) +
        geom_violin(width = 0.8, position = position_dodge(width = 0.8), scale = "width") +
        theme_hd_minimal_plain() +
        theme(
            axis.text.x = element_blank(),  # 旋转横坐标文本
            panel.spacing.x = unit(0, "cm"),                    # 图之间的间距
            panel.spacing.y = unit(0.5, "cm"),
            plot.margin = margin(t = 3, l = ifelse(i == 1, 3, 0), b = 3, r = ifelse(i == nrow(patient_counts), 3, 0))  # 设置边距
        ) +
        labs(title = dataset_name, x= ifelse(i == 4, "Patient", ""),y= ifelse(i == 1, labs_xname, "")) +scale_fill_manual(name="Class",values=c("#00BFFF", "#EE7621")) # 只有第一个图有纵坐标标签
    if(i!=1){
      p= p+theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(),axis.title.y = element_blank())
    }
    plots[[i]] <- p
}
# 使用 ggarrange 将所有图拼接在一起
combined_plot <- ggarrange(plotlist = plots, nrow = 1, ncol = length(plots),common.legend = T,legend = "right",widths = patient_counts$patient_count)

# 显示拼接后的图
return(combined_plot)

}

p_vln1<-plotVlnplot(all_dataset_SCT_filter@meta.data,"nFeature_RNA",'Number of detected genes')
p_vln2<-plotVlnplot(all_dataset_SCT_filter@meta.data,"nCount_RNA",'UMI counts')
p_vln3<-plotVlnplot(all_dataset_SCT_filter@meta.data,"percent.mt",'Percentage of mitochondrial genes')


umap = combined.sct_filter@reductions$umap@cell.embeddings %>%  as.data.frame()  %>% 
  cbind(cell_type =combined.sct_filter@meta.data$Cell_type,dataset=combined.sct_filter@meta.data$dataset,patient=combined.sct_filter@meta.data$patient) 

colors <- c(
  "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b", 
  "#e377c2", "#7f7f7f", "#bcbd22", "#17becf", "#ffbb78", "#ff9896", 
  "#c5b0d5", "#c49c94", "#f7b6d2", "#dbdb8d", "#9edae5", "#f5b0d3", 
  "#c7c7c7", "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", 
  "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf", "#ffbb78", 
  "#ff9896", "#c5b0d5", "#c49c94", "#f7b6d2", "#dbdb8d", "#9edae5", 
  "#f5b0d3", "#c7c7c7", "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", 
  "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf", 
  "#ffbb78", "#ff9896", "#c5b0d5", "#c49c94", "#f7b6d2", "#dbdb8d", 
  "#9edae5", "#f5b0d3"
)
p_patient_umap=ggplot(umap,aes(x=UMAP_1,y=UMAP_2,color=patient))+geom_point(size=0.001)+theme_hd_plain()+facet_wrap(~dataset,nrow=1)+scale_color_manual(values = colors)+
  guides(color = guide_legend(nrow = 4,override.aes = list(size = 4)))+xlab('UMAP 1')+ylab('UMAP 2')


ps1_1<-ggarrange(p_vln1,p_vln2,p_vln3,nrow=3,ncol=1,labels =letters[1:3],font.label = list(size=18,color="black",face="bold"))
ps1_2<-ggarrange(ps1_1,p_patient_umap,nrow=2,ncol=1,labels =c("",letters[4]),font.label = list(size=18,color="black",face="bold"),heights = c(3,1))


pdf(paste("/data/Project/Project1/figures/","supfigure1.pdf",sep=""),height  = 20,width = 17)
print(ps1_2)
dev.off()


tiff(paste("/data/Project/Project1/figures/","supfigure1.tiff",sep=""),height  = 20,width = 17,res = 300,units="in",compression = "lzw")
print(ps1_2)
dev.off()





```

